export const DIAGRAMS: Record<string, string> = {
    'diag-1': 'graph TD\nA-->B',
    'diag-2': 'graph TD\nA-->B',
    'diag-3': 'graph TD\nA-->B',
    'diag-4': 'graph TD\nA-->B',
    'diag-5': 'graph TD\nA-->B',
    'diag-6': 'graph TD\nA-->B',
    'diag-7': 'graph TD\nA-->B',
    'diag-8': 'graph TD\nA-->B',
    'diag-9': 'graph TD\nA-->B',
    'diag-10': 'graph TD\nA-->B',
    'diag-11': 'graph TD\nA-->B',
    'diag-12': 'graph TD\nA-->B',
    'diag-13': 'graph TD\nA-->B',
    'diag-14': 'graph TD\nA-->B',
    'diag-15': 'graph TD\nA-->B',
    'diag-16': 'graph TD\nA-->B',
    'diag-17': 'graph TD\nA-->B',
    'diag-18': 'graph TD\nA-->B',
    'diag-19': 'graph TD\nA-->B',
    'diag-20': 'graph TD\nA-->B',
    'diag-21': 'graph TD\nA-->B',
};
