export type ReferenceLink = [string, string, string];

export const REFERENCE_LINKS: ReferenceLink[] = [
    ['Associate Cloud Engineer Certification | Learn - Google Cloud', 'https://cloud.google.com/learn/certification/cloud-engineer', 'ACE 試験の公式情報ページ'],
    ['Associate Cloud Engineer Certification | Learn | Google Cloud', 'https://cloud.google.com/learn/certification/cloud-engineer?hl=en#exam-guide', '試験ガイドの詳細'],
    ['Compute Engine documentation', 'https://docs.cloud.google.com/compute/docs', 'Compute Engine の公式ドキュメント'],
    ['Set up OS Login | Compute Engine', 'https://docs.cloud.google.com/compute/docs/oslogin/set-up-oslogin', 'OS Login の設定手順'],
    ['Create and use Spot VMs | Compute Engine', 'https://docs.cloud.google.com/compute/docs/instances/create-use-spot', 'Spot VM の作成と使用'],
    ['GKE Autopilot security capabilities', 'https://docs.cloud.google.com/kubernetes-engine/docs/concepts/autopilot-security', 'GKE Autopilot のセキュリティ機能'],
    ['Autopilot vs Standard feature comparison | GKE', 'https://docs.cloud.google.com/kubernetes-engine/docs/resources/autopilot-standard-feature-comparison', 'GKE Autopilot vs Standard の機能比較'],
    ['Cloud Run networking best practices', 'https://docs.cloud.google.com/run/docs/configuring/networking-best-practices', 'Cloud Run ネットワーキングのベストプラクティス'],
    ['Best practices for Cloud Storage', 'https://docs.cloud.google.com/storage/docs/best-practices', 'Cloud Storage のベストプラクティス'],
    ['Your Google Cloud database options, explained', 'https://cloud.google.com/blog/topics/developers-practitioners/your-google-cloud-database-options-explained', 'データベース選定の完全ガイド'],
    ['Best practices and reference architectures for VPC design', 'https://docs.cloud.google.com/architecture/best-practices-vpc-design', 'VPC 設計のベストプラクティスと参考アーキテクチャ'],
    ['Shared VPC overview | Virtual Private Cloud', 'https://docs.cloud.google.com/vpc/docs/shared-vpc', 'Shared VPC の概要と設定'],
    ['6 best practices for running Cloud NAT | Google Cloud Blog', 'https://cloud.google.com/blog/products/networking/6-best-practices-for-running-cloud-nat', 'Cloud NAT 運用のベストプラクティス'],
    ['Best practices for Cloud DNS', 'https://docs.cloud.google.com/dns/docs/best-practices', 'Cloud DNS のベストプラクティス'],
    ['Choosing a load balancer | Cloud Load Balancing', 'https://docs.cloud.google.com/load-balancing/docs/choosing-load-balancer', 'ロードバランサ選定の完全ガイド'],
    ['Terraform best practices for operations | Google Cloud', 'https://docs.cloud.google.com/docs/terraform/best-practices/operations', 'Terraform 運用のベストプラクティス'],
    ['Google Cloud Pricing Calculator', 'https://cloud.google.com/products/calculator', 'クラウドコストの見積もりツール'],
    ['Estimate and control costs | BigQuery', 'https://docs.cloud.google.com/bigquery/docs/best-practices-costs', 'BigQuery コスト管理のベストプラクティス'],
    ['Best practices for Compute Engine regions selection', 'https://docs.cloud.google.com/solutions/best-practices-compute-engine-region-selection', 'Compute Engine リージョン選択のベストプラクティス'],
    ['Choose a Compute Engine deployment strategy for your workload', 'https://docs.cloud.google.com/compute/docs/choose-compute-deployment-option', 'Compute Engine デプロイ戦略の選択'],
    ['Creating a routes-based cluster | GKE networking', 'https://docs.cloud.google.com/kubernetes-engine/docs/how-to/routes-based-cluster', 'Routes-based GKE クラスタの作成'],
    ['Best practices for GKE networking', 'https://docs.cloud.google.com/kubernetes-engine/docs/best-practices/networking', 'GKE ネットワーキングのベストプラクティス'],
    ['Authenticate to Google Cloud APIs from GKE workloads', 'https://docs.cloud.google.com/kubernetes-engine/docs/how-to/workload-identity', 'GKE Workload Identity による認証'],
    ['Cloud run vs cloud functions for serverless | Google Cloud Blog', 'https://cloud.google.com/blog/products/serverless/cloud-run-vs-cloud-functions-for-serverless', 'サーバーレスサービスの選択ガイド'],
    ['General development tips | Cloud Run', 'https://docs.cloud.google.com/run/docs/tips/general', 'Cloud Run 開発の実践ヒント'],
    ['Functions best practices | Cloud Run', 'https://docs.cloud.google.com/run/docs/tips/functions-best-practices', 'Cloud Functions のベストプラクティス'],
    ['Decision tree for data analytics workloads on Google Cloud', 'https://cloud.google.com/blog/products/data-analytics/decision-tree-for-data-analytics-workloads-on-google-cloud', 'データ分析サービスの選定決定木'],
    ['Design an optimal storage strategy for your cloud workload', 'https://docs.cloud.google.com/architecture/storage-advisor', 'ストレージ戦略設計アドバイザー'],
    ['Pick the right storage option on Google Cloud', 'https://cloud.google.com/blog/products/storage-data-transfer/pick-the-right-storage-option-on-google-cloud', 'ストレージオプションの比較と選択'],
    ['AlloyDB for PostgreSQL intelligent scalable storage', 'https://cloud.google.com/blog/products/databases/alloydb-for-postgresql-intelligent-scalable-storage', 'AlloyDB のインテリジェントストレージ解説'],
    ['Virtual Private Cloud (VPC) - Google Cloud', 'https://cloud.google.com/vpc', 'VPC の概要と機能'],
    ['Private Service Connect Features and Benefits', 'https://cloud.google.com/private-service-connect', 'プライベートサービス接続の機能とメリット'],
    ['What is Infrastructure as Code (IaC)? - Google Cloud', 'https://cloud.google.com/discover/what-is-infrastructure-as-code', 'IaC の概念解説'],
    ['Infrastructure as Code on Google Cloud', 'https://docs.cloud.google.com/docs/terraform/iac-overview', 'Terraform による IaC の概要'],
    ['Build a modern three-tier architecture web application with Cloud Run', 'https://developers.google.com/learn/pathways/solution-three-tier-cloud-run', 'Cloud Run の3層アーキテクチャ'],
    ['Jump Start Solution: Three-tier web app', 'https://docs.cloud.google.com/architecture/application-development/three-tier-web-app', '3層 Web アプリのジャンプスタートソリューション'],
];

export const CHAPTER_COUNT = 17;

export const TECH_GUIDE_LINKS: ReferenceLink[] = [
    ['How to Prepare for the Google Cloud Associate Cloud Engineer Exam Core Services', 'https://oneuptime.com/blog/post/2026-02-17-how-to-prepare-for-the-google-cloud-associate-cloud-engineer-exam-core-services-study-guide/view', 'ACE コアサービスの学習ガイド'],
    ['Google Associate Cloud Engineer Exam Guide ... - CloudFluently', 'https://cloudfluently.com/blog/google-associate-cloud-engineer-exam-guide-2026', 'ACE 試験対策ガイド 2026年版'],
    ['Help me pls.. GCP Associate Cloud Engineer : r/googlecloud - Reddit', 'https://www.reddit.com/r/googlecloud/comments/1qzj5kc/help_me_pls_gcp_associate_cloud_engineer/', 'Reddit での ACE 試験対策相談スレッド'],
    ['GCP Pricing Calculator: A Complete Guide - DataCamp', 'https://www.datacamp.com/tutorial/gcp-pricing-calculator', 'GCP 料金計算ツールの完全ガイド'],
    ['Free Practice Questions for Google Associate Cloud Engineer - CertSafari', 'https://www.certsafari.com/google/cloud-engineer-associate', '無料の ACE 練習問題'],
    ['Just passed Associate Cloud Engineer: Resources, Study Tips, and Exam Topics inside', 'https://www.reddit.com/r/googlecloud/comments/1qmn1km/just_passed_associate_cloud_engineer_resources/', 'ACE 合格体験記と学習リソース'],
    ['I just passed the GCP Associate Cloud Engineer exam! : r/googlecloud', 'https://www.reddit.com/r/googlecloud/comments/1j4hvxg/i_just_passed_the_gcp_associate_cloud_engineer/', 'ACE 合格報告と孤独学習のヒント'],
    ['How to Choose Between VPC-Native and Routes-Based GKE Clusters - OneUptime', 'https://oneuptime.com/blog/post/2026-02-17-how-to-choose-between-vpc-native-and-routes-based-gke-clusters/view', 'GKE クラスタタイプの選択'],
    ['VPC native and Route based cluster - KodeKloud', 'https://notes.kodekloud.com/docs/GKE-Google-Kubernetes-Engine/Networking-for-GKE-clusters/VPC-native-and-Route-based-cluster/page', 'GKE ネットワーククラスタの詳解'],
    ['Production grade GKE network deployment, in 3 easy steps.', 'https://medium.com/@pbijjala/3-key-best-practices-for-gke-deployment-4fa132e157e2', 'GKE 本番環境デプロイ3つの鍵'],
    ['Master IAM Concepts for the Google Cloud ACE Certification', 'https://oneuptime.com/blog/post/2026-02-17-how-to-master-iam-concepts-for-the-google-cloud-associate-cloud-engineer-certification/view', 'ACE 試験の IAM コンセプトマスターガイド'],
    ['Exam Associate Cloud Engineer topic 1 question 301 discussion', 'https://www.examtopics.com/discussions/google/view/303709-exam-associate-cloud-engineer-topic-1-question-301/', 'ExamTopics Q301 ディスカッション'],
    ['App Engine vs. Cloud Run: A real-world engineering comparison', 'https://northflank.com/blog/app-engine-vs-cloud-run', 'App Engine vs Cloud Run の実践比較'],
    ['Google App Engine in 2025: Serverless Simplicity vs Cloud Run and GKE', 'https://medium.com/google-cloud/google-app-engine-in-2025-serverless-simplicity-vs-cloud-run-and-gke-d46f485cf908', 'App Engine の2025年現在の位置づけ'],
    ['Google Cloud Functions in 2026: What It Is, Cloud Run vs Functions, Use Cases & Pricing', 'https://www.netcomlearning.com/blog/google-cloud-functions', 'Cloud Functions 入門ガイド 2026'],
    ['How to Choose Between Cloud Run Cloud Functions App Engine and GKE', 'https://oneuptime.com/blog/post/2026-02-17-how-to-choose-between-cloud-run-cloud-functions-app-engine-and-gke-for-your-workload/view', 'サーバーレスサービスの完全選定ガイド'],
    ['The Ultimate Guide to Google Cloud Storage Services and Databases in 2025 - YouTube', 'https://www.youtube.com/watch?v=WdF5fnLR_VY', 'GCS とデータベースの学習ガイド（動画）'],
    ['Google Cloud Pricing: Models, Calculations, & Tips - Veeam', 'https://www.veeam.com/blog/google-cloud-pricing-guide.html', 'Google Cloud 料金モデル解説 1'],
    ['Google Cloud Pricing: The Complete Guide | NetApp', 'https://www.netapp.com/blog/gcp-cvo-blg-google-cloud-pricing-the-complete-guide/', 'Google Cloud 料金モデル詳解 2'],
    ['VPC Networks: GCP Virtual Networking Tutorial for Beginners - YouTube', 'https://www.youtube.com/watch?v=ekpznz8hIzU', 'VPC ネットワーク入門（動画）'],
    ['Private connectivity for AlloyDB: VPC Peering vs Private Service Connect', 'https://medium.com/google-cloud/private-connectivity-for-alloydb-vpc-peering-vs-private-service-connect-3ddf24c64ab6', 'AlloyDB プライベート接続の選択'],
    ['GCP Cloud Engineer Guide: Google Cloud Associate Cloud Engineer Exam Guide', 'https://dev.to/thesius_code_7a136ae718b7/gcp-cloud-engineer-guide-google-cloud-associate-cloud-engineer-exam-guide-38d3', 'GCP Cloud Engineer 完全ガイド 2026'],
    ['Infrastructure as code - YouTube', 'https://www.youtube.com/watch?v=84Ql00Bjh1Y', 'IaC 入門動画'],
    ['How to build a three-tier serverless Cloud Run app - YouTube', 'https://www.youtube.com/watch?v=4URpj0h3mv8', 'Cloud Run 3層アプリ構築動画'],
    ['Google Cloud Spot VMs: Use cases and best practices', 'https://cloud.google.com/blog/products/compute/google-cloud-spot-vm-use-cases-and-best-practices', 'Spot VM のユースケースとベストプラクティス'],
    ['How to Choose Between GKE Autopilot and Standard Mode', 'https://oneuptime.com/blog/post/2026-02-17-how-to-choose-between-gke-autopilot-and-standard-mode-for-your-workload-requirements/view', 'ワークロード要件に応じた GKE モードの選択'],
];
