export type ReferenceLink = [string, string, string];

export const OFFICIAL_DOCS: ReferenceLink[] = [
    ['Associate Cloud Engineer Certification | Learn | Google Cloud', 'https://cloud.google.com/learn/certification/cloud-engineer?hl=en', 'ACE 試験の公式情報ページ'],
    ['Connect to Linux VMs using Identity-Aware Proxy | Compute Engine', 'https://docs.cloud.google.com/compute/docs/connect/ssh-using-iap', 'IAP 経由で Linux VM に SSH 接続'],
    ['Managing clusters | Google Kubernetes Engine (GKE)', 'https://docs.cloud.google.com/kubernetes-engine/docs/how-to/managing-clusters', 'GKE クラスタの管理'],
    ['GKE in the Google Cloud console | GKE', 'https://docs.cloud.google.com/kubernetes-engine/docs/concepts/dashboards', 'GKE のコンソールダッシュボード'],
    ['Viewing Pods and Nodes - Kubernetes', 'https://kubernetes.io/docs/tutorials/kubernetes-basics/explore/explore-intro/', 'Pod とノードの表示'],
    ['Google Kubernetes Engine (GKE)', 'https://cloud.google.com/kubernetes-engine', 'GKE の概要ページ'],
    ['StatefulSet Basics - Kubernetes', 'https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/', 'StatefulSet の基本チュートリアル'],
    ['Using revisions in Cloud Run functions for Traffic Splitting, Gradual Rollouts, and Rollbacks', 'https://codelabs.developers.google.com/codelabs/revisions-2nd-gen-cloud-functions-traffic-splitting-gradual-rollout-rollbacks', 'Cloud Run 関数のリビジョン管理 Codelab'],
    ['Object Lifecycle Management | Cloud Storage', 'https://docs.cloud.google.com/storage/docs/lifecycle', 'オブジェクトのライフサイクル管理'],
    ['Best practices for Cloud Storage', 'https://docs.cloud.google.com/storage/docs/best-practices', 'Cloud Storage のベストプラクティス'],
    ['Create and query a database in the Google Cloud console | Spanner', 'https://docs.cloud.google.com/spanner/docs/create-query-database-console', 'Spanner: コンソールで DB 作成'],
    ['Create and query a database using the Google Cloud CLI | Spanner', 'https://docs.cloud.google.com/spanner/docs/getting-started/gcloud', 'Spanner: gcloud で DB 作成'],
    ['cbt CLI reference | Bigtable', 'https://docs.cloud.google.com/bigtable/docs/cbt-reference', 'cbt CLI リファレンス'],
    ['Introduction to federated queries | BigQuery', 'https://docs.cloud.google.com/bigquery/docs/federated-queries-intro', 'BigQuery 外部データソース入門'],
    ['AlloyDB federated queries | BigQuery', 'https://docs.cloud.google.com/bigquery/docs/alloydb-federated-queries', 'AlloyDB 履歴 BigQuery フェデレートドクエリ'],
    ['Database Center overview | Google Cloud Documentation', 'https://cloud.google.com/database-center/docs/overview', 'Database Center の概要'],
    ['Quickstart: Create and manage VPC networks | Virtual Private Cloud', 'https://docs.cloud.google.com/vpc/docs/using-vpc', 'VPC ネットワークのクイックスタート'],
    ['Reserve a static internal IP address | VPC', 'https://docs.cloud.google.com/vpc/docs/reserve-static-internal-ip-address', '静的内部 IP アドレスの予約'],
    ['Cloud DNS', 'https://cloud.google.com/dns', 'Cloud DNS の概要ページ'],
    ['Create, modify, and delete zones | Cloud DNS', 'https://docs.cloud.google.com/dns/docs/zones', 'Cloud DNS ゾーンの管理'],
    ['Add, update, and delete records | Cloud DNS', 'https://docs.cloud.google.com/dns/docs/records', 'Cloud DNS レコードの管理'],
    ['Alerting overview | Cloud Monitoring', 'https://docs.cloud.google.com/monitoring/alerts', 'アラートの概要'],
    ['Installing the Ops Agent on individual VMs | Google Cloud', 'https://cloud.google.com/stackdriver/docs/solutions/ops-agent/installation', 'Ops Agent のインストール'],
    ['Cloud Trace overview | Google Cloud Documentation', 'https://docs.cloud.google.com/trace/docs/overview', 'Cloud Trace の概要'],
    ['Personalized Service Health | Google Cloud', 'https://cloud.google.com/service-health', 'パーソナライズされたサービスヒールス'],
    ['Active Assist Cloud Management', 'https://cloud.google.com/solutions/active-assist', 'Active Assist による最適化'],
    ['Find recommendations with Active Assist', 'https://docs.cloud.google.com/recommender/docs/quickstart-active-assist', 'Active Assist のクイックスタート'],
    ['Gemini Cloud Assist: AI-assisted cloud operations and management', 'https://cloud.google.com/products/gemini/cloud-assist', 'Gemini Cloud Assist の概要'],
    ['Gemini Cloud Assist documentation', 'https://docs.cloud.google.com/cloud-assist', 'Gemini Cloud Assist ドキュメント'],
    ['Disk snapshot best practices | Compute Engine', 'https://docs.cloud.google.com/compute/docs/disks/snapshot-best-practices', 'スナップショットのベストプラクティス'],
    ['Cloud Monitoring - Google Cloud', 'https://cloud.google.com/monitoring', 'Cloud Monitoring のドキュメント'],
    ['Observability: cloud monitoring and logging - Google Cloud', 'https://cloud.google.com/products/observability', '可観測性製品の一覧'],
    ['Gemini Cloud Assist investigations performs root cause analysis', 'https://cloud.google.com/blog/products/management-tools/gemini-cloud-assist-investigations-performs-root-cause-analysis', 'Gemini Cloud Assist による RCA 解説'],
    ['Cloud Asset Inventory overview', 'https://cloud.google.com/asset-inventory/docs/overview', 'Cloud Asset Inventory の概要'],
    ['Back up and restore a Cloud SQL instance', 'https://docs.cloud.google.com/sql/docs/postgres/backup-recovery/backing-up', 'Cloud SQL バックアップと復元'],
    ['Google Cloud Managed Service for Prometheus', 'https://cloud.google.com/stackdriver/docs/managed-prometheus', 'Managed Service for Prometheus'],
    ['Error Reporting documentation', 'https://cloud.google.com/error-reporting/docs', 'Error Reporting ドキュメント'],
    ['Cloud Trace documentation', 'https://cloud.google.com/trace/docs', 'Cloud Trace ドキュメント'],
];

export const TECH_GUIDES: ReferenceLink[] = [
    ['Set Up SSH Tunneling Through IAP to Reach Compute Engine VMs Without Public IPs', 'https://oneuptime.com/blog/post/2026-02-17-how-to-set-up-ssh-tunneling-through-iap-to-reach-compute-engine-vms-without-public-ips/view', 'IAP SSH トンネル構築ガイド'],
    ['How to Use IAP to Access VMs RDP and SSH in Google Compute Engine - YouTube', 'https://www.youtube.com/watch?v=MQJqSMZrnUA', 'IAP 経由で VM にアクセス（動画）'],
    ['Configuring secure remote access for Compute Engine VMs? | Google Cloud Blog', 'https://cloud.google.com/blog/products/identity-security/configuring-secure-remote-access-for-compute-engine-vms/', 'セキュアなリモートアクセスの設定'],
    ['Google Kubernetes Engine “Important Notes” For Google Certifications (ACE & PCA)', 'https://medium.com/@shreymathuria1989/google-kubernetes-engine-important-notes-for-google-certifications-ace-pca-cf6627f3abad', 'GKE 重要ノート (ACE/PCA)'],
    ['6 Best Practices for Optimizing GKE Costs - Sedai', 'https://sedai.io/blog/6-best-practices-for-optimizing-gke-costs', 'GKE コスト最適化 6つのベストプラクティス'],
    ['GKE Cluster Optimization: 13 Tactics For A Smoother K8s Deployment - Cast AI', 'https://cast.ai/blog/gke-cluster-optimization-13-tactics-for-a-smoother-k8s-deployment/', 'GKE クラスタ最適化の戦術'],
    ['GKE node pool with Autoscaling does not scale down - Stack Overflow', 'https://stackoverflow.com/questions/66642406/gke-node-pool-with-autoscaling-does-not-scale-down', 'GKE ノードプールが縮小しない問題'],
    ['Configure Cloud Run Traffic Splitting to Gradually Roll Out a New Revision', 'https://oneuptime.com/blog/post/2026-02-17-how-to-configure-cloud-run-traffic-splitting-to-gradually-roll-out-a-new-revision/view', 'Cloud Run トラフィック分割の設定'],
    ['Limit Cloud Run Autoscaling Max Instances to Control Costs During Traffic Spikes', 'https://oneuptime.com/blog/post/2026-02-17-how-to-limit-cloud-run-autoscaling-max-instances-to-control-costs-during-traffic-spikes/view', 'Cloud Run オートスケール上限設定'],
    ['Part-41: Google Cloud Run Services - Create Service, Traffic Management, Autoscaling, Revisions', 'https://dev.to/latchudevops/part-41-google-cloud-run-services-create-service-traffic-management-autoscaling-revisions-3c0i', 'Cloud Run トラフィック管理詳解'],
    ['Before you scale: A guide to Cloud Run cost optimization - YouTube', 'https://www.youtube.com/watch?v=0itd33_Mtwo', 'Cloud Run コスト最適化（動画）'],
    ['Which database should I choose? | Medium', 'https://medium.com/google-cloud/which-database-should-i-choose-44be039179ea', 'データベース選定の指针'],
    ['GCP Journey — Day 17: Mastering Google Cloud Databases | Medium', 'https://medium.com/@stephythomaspss/gcp-journey-day-17-mastering-google-cloud-databases-cloud-sql-spanner-bigtable-6f8dff423b82', 'GCP データベースマスターガイド'],
    ['Bigtable command line now supports CSV file importing | Google Cloud Blog', 'https://cloud.google.com/blog/products/databases/bigtable-command-line-now-supports-csv-file-importing/', 'Bigtable CSV インポート'],
    ['Database Center preview now open to all customers | Google Cloud Blog', 'https://cloud.google.com/blog/products/databases/database-center-preview-now-open-to-all-customers', 'Database Center プレビュー'],
    ['Google Cloud Backup: Strategies and Best Practices - Commvault', 'https://www.commvault.com/explore/google-cloud-backup', 'Google Cloud バックアップ戦略'],
    ['What’s new with Google Data Cloud', 'https://cloud.google.com/blog/products/data-analytics/whats-new-with-google-data-cloud-2025', 'Google Data Cloud 2025 最新情報'],
    ['Best practices for managing database fleet health', 'https://docs.cloud.google.com/database-center/docs/best-practices-managing-database-fleet-health', 'データベースフリートの健康管理'],
    ['How to Use GCP Pricing Calculator to Estimate Monthly Cloud Costs', 'https://oneuptime.com/blog/post/2026-02-17-how-to-use-gcp-pricing-calculator-to-estimate-monthly-cloud-costs/view', '料金計算ツールの使い方'],
    ['Part-58: Google Cloud VPC – Internal and External Static IP Addresses - Demo', 'https://dev.to/latchudevops/part-58-google-cloud-vpc-internal-and-external-static-ip-addresses-demo-1c22', '静的 IP アドレス デモ'],
    ['GCP Cloud NAT Gateway | Medium', 'https://dilipkumar.medium.com/gcp-cloud-nat-gateway-5f856cde8272', 'Cloud NAT の基礎'],
    ['How to Handle Cloud Logging - OneUptime', 'https://oneuptime.com/blog/post/2026-01-24-cloud-logging/view', 'Cloud Logging の扱い方'],
    ['Best practices for working with Google Cloud Audit Logs', 'https://cloud.google.com/blog/products/management-tools/best-practices-for-working-with-google-cloud-audit-logging', '監査ログのベストプラクティス'],
    ['How to centralize log management with Cloud Logging | Google Cloud Blog', 'https://cloud.google.com/blog/products/devops-sre/how-to-centralize-log-management-with-cloud-logging', 'ログ管理の集中化手法'],
    ['Google Cloud Logging Cheat Sheet - Tutorials Dojo', 'https://tutorialsdojo.com/google-cloud-logging/', 'Cloud Logging チートシート'],
    ['Why You Need to Enable Audit Logs in Google Cloud | Medium', 'https://medium.com/google-cloud/why-you-need-to-enable-audit-logs-in-google-cloud-0c31578cd4f1', 'なぜ監査ログが必要なのか'],
    ['Introduction to Google Cloud’s operations suite', 'https://cloud.google.com/blog/topics/developers-practitioners/introduction-google-clouds-operations-suite', 'Operations Suite 入門'],
    ['New Personalized Service Health boosts incident response | Google Cloud Blog', 'https://cloud.google.com/blog/products/management-tools/introducing-personalized-service-health', '新しい Service Health の紹介'],
    ['Optimize your cloud by exporting Active Assist recommendations to a BigQuery dataset', 'https://cloud.google.com/blog/products/management-tools/active-assist-bigquery-export/', '推奨を BigQuery にエクスポート'],
    ['Use Gemini Cloud Assist to simplify operational tasks in Google Cloud console - YouTube', 'https://www.youtube.com/watch?v=joEwUqX2OOg', 'Gemini Cloud Assist の活用（動画）'],
];
