// app/gcl/agwa/section2/constants.ts

export type DiagramId =
  | "diag-1"
  | "diag-2"
  | "diag-3"
  | "diag-4"
  | "diag-5"
  | "diag-6"
  | "diag-7"
  | "diag-8"
  | "diag-9"
  | "diag-10"
  | "diag-11"
  | "diag-12"
  | "diag-13";

export const DIAGRAMS: Record<DiagramId, string> = {
  "diag-1": "flowchart LR\n    S2[\"Section 2<br/>コアWorkspaceサービスの管理<br/>約23%\"]\n    S2 --> T1[\"2.1 Gmail<br/>ルーティング・認証・コンプライアンス\"]\n    S2 --> T2[\"2.2 Drive/Docs<br/>共有・ストレージ・ラベル\"]\n    S2 --> T3[\"2.3 Calendar<br/>リソース・共有・委任\"]\n    S2 --> T4[\"2.4 Meet<br/>セーフティ・ビデオ設定\"]\n    S2 --> T5[\"2.5 Chat<br/>スペース・外部連携\"]\n    S2 --> T6[\"2.6 生成AI<br/>Geminiのプライバシーと管理\"]\n    S2 --> T7[\"2.7 開発支援<br/>AppSheet・Apps Script\"]\n\n    classDef heroFill fill:#7c9eff,stroke:#333,stroke-width:2px,color:#000\n    class S2 heroFill",
  "diag-2": "flowchart TD\n    Start[\"メールルーティング要件\"] --> Q1{\"移行・監査目的で<br/>全メールを2箇所に<br/>複製したいか？\"}\n    Q1 -- \"はい\" --> Dual[\"Dual Delivery<br/>（デュアルデリバリー）<br/>Default routing + Also deliver to\"]\n    Q1 -- \"いいえ\" --> Q2{\"ユーザーの一部がGmail、<br/>一部が別メールシステム<br/>（例: 移行期のExchange）か？\"}\n    Q2 -- \"はい\" --> Split[\"Split Delivery<br/>（分割配信）<br/>Add Route + Routing設定\"]\n    Q2 -- \"いいえ\" --> Q3{\"存在しない宛先への<br/>メールを取りこぼしなく<br/>受け取りたいか？\"}\n    Q3 -- \"はい\" --> CatchAll[\"Catch-All メールボックス<br/>Default routing（Unknown recipient）\"]\n    Q3 -- \"いいえ\" --> Custom[\"特定の送信者・件名・<br/>添付・内容に基づく<br/>カスタムRoutingルール\"]\n\n    classDef blueFill fill:#7c9eff,color:#000\n    class Dual,Split,CatchAll,Custom blueFill",
  "diag-3": "flowchart TB\n    Inbound[\"受信メール\"] --> IG{\"インバウンドゲートウェイ<br/>経由か？\"}\n    IG -- \"はい（送信元IPがGateway IPsに一致）\" --> GWCheck{\"Reject all mail not<br/>from gateway IPs が<br/>オンか？\"}\n    GWCheck -- \"オン\" --> RejectOther[\"ゲートウェイ外のIPからの<br/>直接メールは拒否\"]\n    GWCheck -- \"オフ\" --> HeaderEval[\"ヘッダーregexp評価<br/>または通常のGmail<br/>スパム評価を適用\"]\n    IG -- \"いいえ\" --> AllowCheck{\"送信元IPが<br/>Email allowlistに<br/>含まれるか？\"}\n    AllowCheck -- \"はい\" --> BypassSpam[\"標準スパムフィルタを<br/>バイパス（誤検知防止）\"]\n    AllowCheck -- \"いいえ\" --> DenyCheck{\"Blocked senders<br/>（denylist）に<br/>一致するか？\"}\n    DenyCheck -- \"はい\" --> Block[\"メッセージをブロック\"]\n    DenyCheck -- \"いいえ\" --> NormalSpam[\"通常のGmail<br/>スパム・フィッシング・<br/>マルウェア判定\"]\n\n    classDef blueFill fill:#7c9eff,color:#000\n    classDef redFill fill:#e57373,color:#000\n    class BypassSpam blueFill\n    class Block,RejectOther redFill",
  "diag-4": "sequenceDiagram\n    participant Sender as 送信元<br/>（Google Workspace）\n    participant DNS as 送信ドメインのDNS\n    participant Receiver as 受信側メールサーバー\n\n    Sender->>DNS: SPFレコード公開<br/>（\"どのIPが送信を許可されるか\"）\n    Sender->>DNS: DKIM公開鍵をTXTレコードで公開\n    Sender->>DNS: DMARCポリシー(p=none/quarantine/reject)を公開\n\n    Sender->>Receiver: メール送信（DKIM署名付与）\n    Receiver->>DNS: SPFレコードを検証<br/>（送信元IPが許可リストにあるか）\n    Receiver->>DNS: DKIM公開鍵を取得し署名を検証\n    Receiver->>Receiver: SPF/DKIMとFromヘッダーの<br/>ドメイン一致(alignment)を確認\n    Receiver->>DNS: DMARCポリシーを取得\n    Receiver->>Receiver: ポリシーに従い配信/隔離/拒否を判定",
  "diag-5": "flowchart TD\n    Rule[\"ファイル共有アクション\"] --> Check{\"Trust Rulesの<br/>条件に一致するか？<br/>（OU・グループ・ドメイン・ユーザー単位）\"}\n    Check -- \"Allow\" --> Allowed[\"共有を許可\"]\n    Check -- \"Deny\" --> Denied[\"共有をブロック\"]\n    Check -- \"Warn\" --> Warned[\"警告を表示した上で<br/>ユーザーの判断に委ねる\"]\n    Check -- \"一致なし\" --> Fallback[\"デフォルトの<br/>Drive共有設定/<br/>ターゲットオーディエンス設定を適用\"]\n\n    classDef blueFill fill:#7c9eff,color:#000\n    classDef redFill fill:#e57373,color:#000\n    classDef yellowFill fill:#ffd54f,color:#000\n    class Allowed blueFill\n    class Denied redFill\n    class Warned yellowFill",
  "diag-6": "flowchart LR\n    MyDrive[\"マイドライブ<br/>（個人所有）\"] -->|\"退職・異動時に<br/>所有権移転が必要\"| Risk[\"データ喪失リスク\"]\n    SharedDrive[\"共有ドライブ<br/>（チーム/組織所有）\"] -->|\"メンバー変更があっても<br/>ファイルは残る\"| Stable[\"データの継続性\"]\n\n    SharedDrive --> OU1[\"OUに割り当て\"]\n    OU1 --> Policy[\"OU固有のポリシー継承<br/>（共有・ストレージ上限・セキュリティ）\"]\n\n    classDef blueFill fill:#7c9eff,color:#000\n    class SharedDrive,Stable blueFill",
  "diag-7": "flowchart TD\n    NewFile[\"新規ファイル作成/<br/>所有権移転/<br/>共有ドライブへの移動\"] --> Method{\"ラベル自動適用方式\"}\n    Method -->|\"1. デフォルト分類\"| Default[\"Default classification<br/>OU/グループ単位で<br/>既定ラベル値を自動付与\"]\n    Method -->|\"2. DLPルール\"| DLP[\"DLPルールの検出条件に<br/>一致した場合にラベルを付与\"]\n    Method -->|\"3. AI分類\"| AI[\"Geminiによる<br/>コンテンツ内容の<br/>自動分類・ラベル付与\"]\n\n    Default -.優先順位.-> Priority[\"DLPラベル値 > AI分類ラベル値<br/>> デフォルト分類ラベル値<br/>（同種のルールが競合する場合は<br/>ラベルの選択肢リストでより上位の値が優先）\"]\n    DLP -.-> Priority\n    AI -.-> Priority\n\n    classDef yellowFill fill:#ffd54f,color:#000\n    class Priority yellowFill",
  "diag-8": "flowchart TD\n    Book[\"ユーザーがリソースを<br/>会議に招待\"] --> AutoAccept{\"リソースの<br/>Auto-accept invitations<br/>設定\"}\n    AutoAccept -- \"競合しない招待を<br/>自動承認\" --> CheckConflict{\"時間帯が<br/>既存予約と<br/>競合するか？\"}\n    CheckConflict -- \"競合なし\" --> Confirmed1[\"自動的に予約確定\"]\n    CheckConflict -- \"競合あり\" --> Declined1[\"自動的に辞退\"]\n    AutoAccept -- \"すべての招待を<br/>カレンダーに追加<br/>（リソースマネージャー運用）\" --> Manager[\"リソースマネージャーに通知\"]\n    Manager --> Decision{\"マネージャーが<br/>確認\"}\n    Decision -- \"承認\" --> Confirmed2[\"予約確定\"]\n    Decision -- \"却下/変更依頼\" --> Declined2[\"辞退\"]\n\n    classDef blueFill fill:#7c9eff,color:#000\n    classDef redFill fill:#e57373,color:#000\n    class Confirmed1,Confirmed2 blueFill\n    class Declined1,Declined2 redFill",
  "diag-9": "flowchart TD\n    HM[\"Host Management<br/>（ホスト管理）\"] -->|\"オン\"| HMOn[\"ホスト・co-hostのみが<br/>以下を制御可能：\"]\n    HMOn --> C1[\"チャットの許可\"]\n    HMOn --> C2[\"画面共有の許可\"]\n    HMOn --> C3[\"リアクション・Q&A・投票の許可\"]\n    HMOn --> C4[\"参加者の全員ミュート/解除\"]\n    HMOn --> C5[\"録画・文字起こしの開始権限\"]\n\n    HM -->|\"オフ\"| HMOff[\"同一ドメインの参加者は<br/>誰でも上記操作が可能<br/>（既定の緩い状態）\"]\n\n    Waiting[\"Waiting Room<br/>（待機室）\"] -->|\"Quick accessが<br/>オフの場合に有効\"| WaitFlow[\"参加者は待機室で<br/>ホストの承認を待つ\"]\n    QuickAccess[\"Quick access<br/>（クイックアクセス）\"] -->|\"オンの場合\"| QAFlow[\"カレンダー招待に含まれる<br/>参加者はホスト不在でも<br/>入室可能\"]\n\n    classDef blueFill fill:#7c9eff,color:#000\n    class HMOn,WaitFlow blueFill",
  "diag-10": "flowchart LR\n    Meeting[\"Meet設定\"] --> Video[\"ビデオ設定\"]\n    Video --> Quality[\"既定の画質\"]\n    Video --> Rec[\"録画<br/>（既定3か月保存）\"]\n    Video --> Trans[\"文字起こし<br/>（音声のみ、Drive保存）\"]\n    Video --> Notes[\"Gemini ノートテイキング<br/>（Business/Enterprise/Education<br/>アドオンが必要）\"]\n\n    Rec -.HostManagementの制約.-> HMcheck[\"ホスト管理がオン かつ<br/>ホストが許可していない場合は<br/>録画不可\"]\n\n    classDef blueFill fill:#7c9eff,color:#000\n    class Rec,Trans,Notes blueFill",
  "diag-11": "flowchart TD\n    Ext[\"組織外とのChat連携\"] --> Q1{\"1対1/スペース単位で<br/>組織外とメッセージ<br/>送受信を許可するか？\"}\n    Q1 -- \"On\" --> Trust{\"信頼済みドメイン<br/>（allowlist）のみに<br/>制限するか？\"}\n    Trust -- \"はい\" --> Restricted[\"特定ドメインとのみ<br/>外部Chatを許可\"]\n    Trust -- \"いいえ\" --> AnyExternal[\"任意の外部ドメインと<br/>Chat可能\"]\n    Q1 -- \"Off\" --> NoExternal[\"外部とのメッセージ<br/>送受信を禁止\"]\n\n    Q1 --> Q2{\"外部スペース<br/>（External spaces）を<br/>許可するか？\"}\n    Q2 -- \"はい\" --> ExtSpace[\"メンバー・認可されたChatアプリが<br/>外部ユーザー/ゲストを招待可能\"]\n    Q2 -- \"いいえ\" --> NoExtSpace[\"スペースへの<br/>外部ユーザー招待不可\"]\n\n    classDef blueFill fill:#7c9eff,color:#000\n    classDef yellowFill fill:#ffd54f,color:#000\n    classDef redFill fill:#e57373,color:#000\n    class Restricted blueFill\n    class AnyExternal yellowFill\n    class NoExternal redFill",
  "diag-12": "flowchart TD\n    Layer1[\"レイヤー1: Workspaceサービス内のGemini機能<br/>（Gmail/Docs/Sheets/Slides/Driveのサイドパネル）\"]\n    Layer2[\"レイヤー2: Geminiアプリ（gemini.google.com）へのアクセス\"]\n    Layer3[\"レイヤー3: Geminiアプリ内でのWorkspace拡張機能<br/>（旧Workspace Extensions/Apps）\"]\n\n    Layer1 -->|\"Admin console →<br/>生成AI → Gemini for Workspace →<br/>Feature access\"| L1Detail[\"サービスごとに個別On/Off<br/>（あるアプリでオフでも、<br/>別アプリ経由でそのデータに<br/>アクセスされる場合がある点に注意）\"]\n    Layer2 -->|\"Admin console →<br/>Turn the Gemini app on/off\"| L2Detail[\"既定で18歳以上かつ<br/>ライセンス保有ユーザーに提供。<br/>全ユーザーへの拡大も可能\"]\n    Layer3 -->|\"Admin console →<br/>Turn Google apps in Gemini on/off\"| L3Detail[\"Calendar/Docs/Drive/Gmail/<br/>Keep/TasksのコンテンツをGeminiアプリの<br/>プロンプトに利用可能にするか\"]\n\n    classDef blueFill fill:#7c9eff,color:#000\n    class Layer1,Layer2,Layer3 blueFill",
  "diag-13": "flowchart LR\n    Need[\"業務自動化の要件\"] --> Q{\"要件の性質は？\"}\n    Q -->|\"データ駆動型の<br/>業務アプリ・モバイルUIが必要<br/>（現場担当者向けフォーム、<br/>在庫管理、承認ワークフロー等）\"| AppSheet[\"AppSheet<br/>（ノーコードアプリ開発）\"]\n    Q -->|\"既存のWorkspaceアプリの<br/>内部処理をカスタムコードで<br/>自動化したい<br/>（トリガー起動のスクリプト、<br/>カスタム関数、API連携）\"| AppsScript[\"Apps Script<br/>（JavaScriptベースの<br/>クラウドスクリプト実行基盤）\"]\n\n    AppSheet -.連携可能.-> AppsScript\n    AppsScript -.複雑なロジックを提供.-> AppSheet\n\n    classDef blueFill fill:#7c9eff,color:#000\n    class AppSheet,AppsScript blueFill"
};
